spring.application.name=vehiculos


server.port=8095
spring.datasource.username=root
spring.datasource.password=miku123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.datasource.url=jdbc:mysql://localhost:3306/localmysql
spring.datasource.url=jdbc:mysql://18.209.57.102:3306/vehiculos


#opcional: (mostrar en consola las consultas)
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update