spring.application.name=compra



spring.datasource.url=jdbc:mysql://labasedelamiku.c5wo7kzpbj8x.us-east-1.rds.amazonaws.com

spring.datasource.username=admin
spring.datasource.password=chocolate

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.application.version = 1.0

spring.jpa.hibernate.ddl-auto=create
